version: "3"

services:
    fcm_redis:
        image: redis:3.2.6-alpine
        container_name: fcm_redis
        links:
            - node1:node1
        volumes:
            - redis_data:/data/fcm
            
    fcm_node1:
        env_file: .env
        image: readytalk/nodejs
        links:
            - fmc_redis
        ports:
            - "${PORT}"
        networks:
        - front
        - back

networks:
    front:
    back:

volumes:
  redis_data: