version: "3"

services:
  nap:
    container_name: nap
    env_file: .env
    environment:
      - HTTP_PORT=${HTTP_PORT:-3000}
    image: rabbotio/nap
    restart: always
    links:
      - redis
      - mongo
    working_dir: /usr/app
    ports:
      - "5858:5858" # Node Inspector port
      - "${HTTP_PORT:-3000}:${HTTP_PORT:-3000}" # HTTP port
    volumes:
      - ./.env:/usr/app/.env
      - ./pages:/usr/app/pages
      - ./components:/usr/app/components
      - ./public:/usr/app/public
      - ./lib:/usr/app/lib
      - ./routes:/usr/app/routes
      - ./graphql:/usr/app/graphql
      - ./providers:/usr/app/providers # __DEV__
      - ./server:/usr/app/server # __DEV__
    build: . # __DEV__
    command: npm run _build-back # Will build next and run express server
    networks:
      - front
      - back

  redis:
    image: redis:3.2.6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - back

  mongo_data:  
    image: mongo:3.4
    container_name: mongo_data
    command: bin/true
    networks:
      - back

  mongo:  
    image: mongo:3.4
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: always
    command: --smallfiles --rest
    networks:
      - back

networks:
  front:
  back:

volumes:
  redis_data:
  mongo_data: