version: "3"

services:
  nap:
    container_name: nap
    env_file: .env
    environment:
      - PORT=${PORT:-3000}
    image: rabbotio/nap
    restart: on-failure
    links:
      - redis
      - mongo
    working_dir: /usr/app
    ports:
      - "${PORT:-3000}:${PORT:-3000}" # HTTP port
    volumes:
      - ./.env:/usr/app/.env
      - ./pages:/usr/app/pages
      - ./components:/usr/app/components
      - ./public:/usr/app/public
      - ./lib:/usr/app/lib
      - ./routes:/usr/app/routes
      - ./graphql:/usr/app/graphql
      - ./templates:/usr/app/templates
    command: npm run _prod
    networks:
      - front
      - back

  redis:
    image: redis:3.2.6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: on-failure
    volumes:
      - redis_data:/data
    networks:
      - back

  mongo_data:  
    image: mongo:3.4
    container_name: mongo_data
    command: bin/true
    networks:
      - back

  mongo:  
    image: mongo:3.4
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: on-failure
    command: --smallfiles --rest
    networks:
      - back

networks:
  front:
  back:

volumes:
  redis_data:
  mongo_data: